fix: cd script

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -73,21 +73,20 @@ jobs:
                     continue
                 fi
 
-                echo "Building image: $image"
-                if ! npx nx run "$image":build; then
-                    echo "Error: Failed to build image $image"
+                echo "Building image: \$image"
+                if ! npx nx run "\$image":build; then
+                    echo "Error: Failed to build image \$image"
                     continue
                 fi
 
                 echo "Building docker image: $image"
                 docker build -t "nebur242/izistore-backend-microservices:\$image"  "dist/apps/\$image"
 
-                echo "Loading image into kind: $image"
+                echo "Loading image into kind: \$image"
                 if ! kind load docker-image "nebur242/izistore-backend-microservices:\$image"; then
                    echo "Error: Failed to load image into kind."
                    continue
                 fi
-                echo "Image successfully loaded into kind."
 
                 echo "Image successfully loaded into kind."
             done
