chore: improve code cd

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -23,6 +23,7 @@ jobs:
       EC2_USER: ${{ secrets.EC2_USER }}
       EC2_TARGET_PATH: /home/${{secrets.EC2_USER}}/izistore-backend-microservices
       KUBECONFIG_PATH: /home/${{secrets.EC2_USER}}/.kube/config
+      KIND_CLUSTER: izistore-api
 
     steps:
       - name: Checkout code
@@ -30,6 +31,14 @@ jobs:
 
       - name: Install rsync
         run: sudo apt-get update && sudo apt-get install rsync -y
+
+      - name: Install Doppler CLI
+        uses: dopplerhq/cli-action@v3
+
+      - name: Fetch Doppler Secrets
+        run: |
+          doppler configure set token ${{ secrets.DOPPLER_TOKEN }}
+          doppler secrets --project izistore --config prd --token "${{ secrets.DOPPLER_TOKEN }}" download --format=env --no-file > .env
 
       - name: Add SSH key
         uses: webfactory/ssh-agent@v0.7.0
@@ -43,9 +52,20 @@ jobs:
       - name: Pull Images from Docker Hub and Deploy to Kind Cluster
         run: |
           ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << EOF
+            set -e  # Exit immediately if a command exits with a non-zero status
+
             sudo su
 
-            cd ${EC2_TARGET_PATH}
+            # Switch to the deployment directory
+            cd \$EC2_TARGET_PATH
+
+            # Install global dependencies
+            echo "Installing global dependencies..."
+            npm install -g nx
+
+            # Install project dependencies
+            echo "Installing project dependencies..."
+            npm ci
 
             # Add user to docker group if it doesn't exist and refresh session
             if ! groups $EC2_USER | grep -q docker; then
@@ -53,17 +73,14 @@ jobs:
                newgrp docker
             fi
 
-            # Login to Docker Hub (If needed for private images)
-            # docker login --username "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
-            
-            npm install -g nx
-
-            npm install
-
             # Pull and load images to Kind cluster
             images=("api-gateway")
 
+            #swith kubectl context
+            kubectl config use-context "kind-\$KIND_CLUSTER"
+
             for image in \${images[@]}; do
+                echo "Processing image: \$image"
 
                 if [ -z "\$image" ]; then
                     echo "Skipping empty image name."
@@ -71,28 +88,23 @@ jobs:
                 fi
 
                 echo "Building image: \$image"
-                if ! npx nx run "\$image":build; then
-                    echo "Error: Failed to build image \$image"
-                    continue
-                fi
+                npx nx run "\$image":build || { echo "Failed to build $image"; continue; }
+
+                echo "Copy env vars to \$image"
+                cp .env "dist/apps/\$image"
 
                 echo "Building docker image: $image"
                 docker build -t "nebur242/izistore-backend-microservices:\$image"  "dist/apps/\$image"
 
-                echo "Loading image into kind: \$image"
-                if ! kind load docker-image "nebur242/izistore-backend-microservices:\$image" --name=izistore-api ; then
-                   echo "Error: Failed to load image into kind."
-                   continue
-                fi
+                 # Load image into Kind
+                echo "Loading image into Kind for \$image..."
+                kind load docker-image "nebur242/izistore-backend-microservices:\$image" --name=\$KIND_CLUSTER || { echo "Failed to load $image into Kind"; continue; }
 
-                echo "Image successfully loaded into kind."
+                # Apply Kubernetes manifests
+                echo "Applying Kubernetes manifests for \$image..."
+                kubectl apply -f "kubernetes/\$image" || { echo "Failed to apply manifests for $image"; continue; }
+                echo "kubernetes config successfully set..."
             done
 
-            #swith kubectl context
-            kubectl config use-context kind-izistore-api
-
-            # Apply Kubernetes manifests
-            echo "Applying kubernetes manifests"
-            kubectl apply -f kubernetes/
             echo "Deployment Complete!"
           EOF
