chore: improve code cd

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -88,7 +88,7 @@ jobs:
                 fi
 
                 echo "Building image: \$image"
-                npx nx run "\$image":build || { echo "Failed to build $image"; continue; }
+                nx run "\$image":build || { echo "Failed to build $image"; continue; }
 
                 echo "Copy env vars to \$image"
                 cp .env "dist/apps/\$image"
